#!/usr/bin/env python
from rucio.api.did import set_new_dids, list_dids

filters = {
    "name": "/*/MINIAOD",
}

didlist = (
    {"scope": "cms", "name": did}
    for i, did in enumerate(list_dids(scope="cms", filters=filters, type="container"))
    if "RelVal" not in did
)

for did in didlist:
    set_new_dids([did])

